name: Code checks

on:
  pull_request:
    branches: [ main ]

jobs:
  linting:
    name: Run linting checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install flake8

      - name: Run linting tests
        run: |
          flake8 src/model/

  placeholder:
    name: Placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Run a placeholder script
        run: |
          echo "Will add code checks here in next challenge"
